### PR TITLE
Added numbers to the vehicle categories

### PR DESCRIPTION
**Pull request by BreakinBenny**
Paradise Cars shows first if all 8 are shown at once, from up to down.

### CODE REVIEW

**Comment by burninrubber0** [comment]
I'm a little confused as to why this is necessary. Paradise Cars should always be first in the list. Is the list changing order when you use it?

**Comment by BreakinBenny** [comment]
No, I'm only mentioning because the categories go like this normally (at least when in vanilla). Paradise Cars (Category 1) is always on top unless somehow nothing from that is unlocked, which would instead put Paradise Bikes (Category 2) there.

Online Cars usually occupies slot 3 if the Rai-Jin Turbo and Olympus aren't moved from there, which would move the Big Surf Island Cars off the list a bit. Besides, I modded my VEHICLELIST.BUNDLE to sort the categories based on when the rides came out. (The two Cagney cars' graphics are also sorted among the base game's vehicle icons. I practically merged the Toy Vehicles and other two DLC pack categories into one, mainly for organization.)


…It was mainly a fun idea I had, but it does make room for renaming the Online Cars category to involve miscellaneous cars + those from mods (like in the BPR Expansion) without "BSI" being moved off the list that can only show 7 categories at once properly.

**Comment by burninrubber0** [comment]
I'm still not entirely sure how the numbers are useful - are you able to clarify? You mention how Bikes would be first if there weren't any Paradise Cars, but in that situation, numbering the categories would make it more confusing since Bikes would be listed as (2) while being the first category in-game.

**Comment by BreakinBenny** [comment]
I don't have a lot on it, actually. I can only say that Paradise Cars is where vehicles with an 01 for the category ID wind up, though the carbon fiber cars might have a different one and mainly go there because of their VEHICLELIST.BUNDLE flags.

…Bikes end up in 02, which is normally the second one to show. I can't be sure where I want to go with this myself.

**Comment by burninrubber0** [comment]
It sounds like you're trying to match them to their hex values, but in that case, all numbers beyond 2 are incorrect. Online Cars are actually 4, Toys are 8, and so on. This is because the category field is made up of binary flags:
https://github.com/burninrubber0/Bundle-Manager/blob/b468ea4bb4634985031dc6d426e2cda04a7cb396/VehicleList/VehicleListData.cs#L79-L91
As it doesn't provide any real benefit, I'm closing this PR. Glad you want to contribute, though.

**Pull request closed without merging**
