### PR TITLE
Add Trigger Editor

### PR DESCRIPTION
**Pull request by derneuere**
This pull request adds another property grid for editing the triggers. It also implements reading and writing section4Entry data.

### CODE REVIEW

**Comment by burninrubber0** [comment]
Similar situation to #22, lots of offsets and counts and such that should be hidden. A 3D editor would be best but after reading what was said in Discord that probably won't be feasible for the foreseeable future, so the collection editor works well enough here.

On a personal note, it's good to see an editor for triggers going public, so keep it coming :)

**Review by burninrubber0 — CHANGES_REQUESTED** [review]
A few issues came up in testing. The biggest one is that almost all triggers (GenericRegions, Killzones, RoamingLocations, and others) crashed BM upon pressing OK after having one entry added to their array. It looks like this is because certain objects (mainly base TriggerRegions and Vector3s) are not created. Given the way it's done, you might have to fix and test each trigger type individually.

When the editor got far enough to save the edited bundle, attempting decompression afterward crashed DGI's Noesis unpacker. I didn't test it with the game, but in the past this has always translated to in-game issues. It's possible this is an existing issue with BM's Bundle code but it's hard to say without further troubleshooting.

Aside from these bugs, the editor itself looks decent. The only thing I'd recommend is automatically recalculating `muSize` upon saving and not exposing the field to the user. Maybe I'll have more suggestions after fixes are implemented, but the way the editor works now seems alright.

**Comment by derneuere** [comment]
The muSize seems to get recalculated correctly, but I think you have to close and open it again.
Fixed the issues, seemed to be that I didn't initialize the values.

I am unfamiliar with DGI's Noesis unpacker. Any steps I could follow to test that?

**Review by burninrubber0 — CHANGES_REQUESTED** [review]
Latest commit fixed the majority of the issues, but there are still crashes when opening a new Killzone's RegionIds collection editor or opening either of StartingGrid's Vector3I collection editors. Otherwise, it seems stable.

In the editor, TriggerRegion's `mBoxRegion` needs to be editable. CgsIDs also appear read-only unless part of a collection (see the SignatureStunt and SpawnLocation editors).

It might also be worth using enums for the [Blackspot ScoreType](https://burnout.wiki/wiki/Trigger_Data#BrnTrigger::Blackspot::ScoreType) and [GenericRegion Type](https://burnout.wiki/wiki/Trigger_Data#BrnTrigger::GenericRegion::Type) like the TriggerRegion Type does, as well as setting the correct TriggerRegion Type on Blackspots and GenericRegions like is done with VFXBoxRegions.

I looked through the output file after making a few changes and everything looked correct, so after the above is addressed it should be good to go. I confirmed the Bundle issue mentioned earlier is a separate, known bug, #13.

**Comment by derneuere** [comment]
I can't really reproduce the issue with the killzone region IDs.
StartingGrids should not get saved yet, as it's unclear where it's saved within the file.

Added enums and editors for Vector3I and CgsIDs and explained that you have to use the region.mid for trigger ids in killzone :)

**Comment by burninrubber0** [comment]
Clicking Add in the Killzone editor now results in this:
image

Based on the triggers in the Feb 22 2007 build, StartingGrids are written after SpawnLocations in the file, but before the TriggerRegion pointers. Also of some relevance, stunt elements for SignatureStunts are written after StartingGrids. Neither of these have entries in any retail version of the game, so it's up to you whether to support them or not.

Previously read-only fields are editable now, so that looks good. Enums look good too, thanks for adding them.

**Comment by derneuere** [comment]
Thanks for the info! Added writing for the starting grids and the signature stunt elements.
Adding should work now, had to refactor all arrays to lists :)

**Comment by derneuere** [comment]
Alright, found the bug, should work now :)

**Comment by burninrubber0** [comment]
Nice, that's a good improvement, I think we're just about there for real now.

The Killzone region IDs issue mentioned earlier is still present. Here's a video of it so you can reproduce:
https://user-images.githubusercontent.com/17496749/234901161-a63d57d7-d34b-4b78-9c7b-57b7c5fb902d.mp4

When adding a new vector to either collection in a starting grid, I received this error:
image

Also, SignatureStunt's `mId` is not editable.

**Comment by derneuere** [comment]
Could not recreate the bug for RegionIDs even with the video. Weird. I switched it to a list, which should probably work for you too, as other lists seem to work.

Added a default constructor for Vector3I and made mId editable :)

**Comment by burninrubber0** [comment]
Yep, that fixed all the issues remaining. I'll take one last look and see if there's anything left to do before merging.

**Comment by burninrubber0** [comment]
Merging. Normally this would warrant a new release but I'll try to address #13 first.

**Pull request merged**
