### PR TITLE
LUAList Editor

### PR DESCRIPTION
**Pull request by derneuere**
This pull request implements reading and writing the LUAList and the LUAList Entry.

I am not sure yet on how to test this. Any help figuring out when a LUAScript is used would be appreciated.

### CODE REVIEW

**Comment by burninrubber0** [comment]
As far as I know, the only ones accessible in the vanilla game are the Pass The Pad (Party) scripts. The others are for a cut feature called scripted challenges. That's been accessed by a few people but there's still no public way of running them.

Testing should be easy enough through Party mode, but it might take a while to land on a specific script.

**Comment by derneuere** [comment]
Oh no, that means I can't test it, as online mode never worked for me. I always have to play in offline mode, otherwise the game crashes 😅

**Comment by burninrubber0** [comment]
Yikes, might want to contact Bo about that. There's also this updated version of the Core Bugfixes you should try after installing the normal version through [BPR Modder](https://bpr.bo98.uk) - it weeds out most of the bugs I know about.
[core-bugfixes.zip](https://github.com/burninrubber0/Bundle-Manager/files/8647014/core-bugfixes.zip)

**Comment by derneuere** [comment]
I figured out why it wasn't working! I had a couple of friends who deleted their accounts and bpr could not handle that. Would be great if this could be fixed in a future core bugfix release.

**Comment by burninrubber0** [comment]
Finally got the chance to test this. It works but ends up feeling super clunky. Lots of padding, pointers, and lengths showing up when they should all be hidden and automatically taken care of. Also still needs CgsIDs to be decoded, looks like.

I'd say this is a good starting point for testing whether it saves properly and such, but a custom editor is needed for it to be worthwhile - perhaps similar to the VehicleList editor (but smaller, because the VehicleList is massive).

**Comment by derneuere** [comment]
Alright, I have removed all paddings, pointers and lengths, and they should get taken care of automatically.  I also replaced all unknown fields with the types defined in the specification.

The UI is now functional enough for now, and I want to finish the other PRs first. I will then address UI concerns in a future PR.

**Review by burninrubber0 — APPROVED** [review]
Everything looks complete and accurate now, nice work.

The one thing I noticed was the type and variables fields in entries are displayed as integers when they're really binary flags, but looking at them now I think any changes to them are best left for another PR.

Merging.

**Pull request merged**
